### ISSUE TITLE
Black Screen on Reboot

### ISSUE THREAD

**Issue by RainehDaze** [luisbocanegra/plasma-smart-video-wallpaper-reborn#12]
Odd, boot-related issue here. On rebooting, both wallpapers (I have two monitors) will be black, but if I change them to some other wallpaper type and _then_ set it back to smart wallpaper, they'll work normally--is there potentially some configuration or startup option missing?

This is after changing to gstreamer as ffmpeg as a backend seemed to be even worse about this, sometimes never starting at all regardless of how things are toggled.

[sysinfo.txt](https://github.com/luisbocanegra/plasma-smart-video-wallpaper-reborn/files/15048608/sysinfo.txt)

Or is it that some other dependency is oddly missing? Trying to run the test file with qml6 simply returns command not found, and replacing it with plain qml prompts a suggestion to install `qt5-qtdeclarative-devel`, which seems odd.

**Comment by luisbocanegra** [comment]
Install **qt6-qtdeclarative-devel** and run the test.qml as per the instructions using `qml-qt6`

**Comment by RainehDaze** [comment]
Hm, that worked aside from the pausing, although after a while it just showed a grey screen. Doesn't look like there's any other issues in the output, though--not that I really expected them, since it's not a crashing problem I'm facing. 

[qmlout.txt](https://github.com/luisbocanegra/plasma-smart-video-wallpaper-reborn/files/15049414/qmlout.txt)

Maybe I need to log things at boot?

**Comment by luisbocanegra** [comment]
Sorry, the gray screen is due to the absence of a local video (initially this file was for https://github.com/luisbocanegra/plasma-smart-video-wallpaper-reborn/issues/7) I removed it now.

> Maybe I need to log things at boot?

Yes, please reboot and after logging to the black video run `journalctl -b > journal.txt` let it run for a couple of seconds, terminate it and send the file.

**Comment by RainehDaze** [comment]
Will do, unfortunately it seems like this isn't happening every time I reboot (just often enough to be annoying). Don't think there's anything super weird in the boot log where it does start, looking at it.

**Comment by RainehDaze** [comment]
[journal.txt](https://github.com/luisbocanegra/plasma-smart-video-wallpaper-reborn/files/15055010/journal.txt)

**Comment by luisbocanegra** [comment]
Unfortunately `plasmashell[2649]: qt.multimedia.player: Unable to set the pipeline to the paused state.` is not very informative

Can you try running the test.qml and test testMediaPlayer.qml and try to reproduce the bug with that?

e.g:

`QSG_INFO=1 QT_LOGGING_RULES="qml.debug=true" qml-qt6 test.qml`

**Comment by RainehDaze** [comment]
[testMediaPlayerOut.txt](https://github.com/luisbocanegra/plasma-smart-video-wallpaper-reborn/files/15055528/testMediaPlayerOut.txt)
[testout.txt](https://github.com/luisbocanegra/plasma-smart-video-wallpaper-reborn/files/15055529/testout.txt)

Doesn't reproduce the "won't start" bug. Does reproduce another weird one, though--the playback _not unpausing_ when I click play (I've seen playback freeze entirely unless I set it to 'never pause' and then change the video manually to get it started again). Although, it seems like this is rather sparse for debug output? Unless I'm missing something.

**Comment by luisbocanegra** [comment]
> [testMediaPlayerOut.txt](https://github.com/luisbocanegra/plasma-smart-video-wallpaper-reborn/files/15055528/testMediaPlayerOut.txt) [testout.txt](https://github.com/luisbocanegra/plasma-smart-video-wallpaper-reborn/files/15055529/testout.txt)
> 
> Doesn't reproduce the "won't start" bug. Does reproduce another weird one, though--the playback _not unpausing_ when I click play (I've seen playback freeze entirely unless I set it to 'never pause' and then change the video manually to get it started again). Although, it seems like this is rather sparse for debug output? Unless I'm missing something.

You are absolutely right! Please test with:

`QSG_INFO=1 QT_LOGGING_RULES="*.debug=true" qml6 /home/luis/projects/plasma-smart-video-wallpaper/playground/000videoTestMediaPlayer.qml`

**Comment by RainehDaze** [comment]
[testout.txt](https://github.com/luisbocanegra/
[testmediaplayeroutverbose.txt](https://github.com/luisbocanegra/plasma-smart-video-wallpaper-reborn/files/15055628/testmediaplayeroutverbose.txt)
plasma-smart-video-wallpaper-reborn/files/15055610/testout.txt)

Interesting observation: pausing and unpausing works for the little chrome dongle clip, but not the other one.

**Comment by RainehDaze** [comment]
So, I think I solved the black screen issue (if not the "can't start after pausing" issue--want me to open that as a new one or just rename this?), but I'll note again if things didn't work: my wallpaper files were on _another drive._ When I moved those over to my home partition instead, rebooting and just shutting down and starting normally _seems_ to have things start up perfectly fine.

Although, those other drives are mounted on startup too, so not sure why that would present an issue, but it's all I can really imagine is influencing it.

**Comment by luisbocanegra** [comment]
> [testmediaplayeroutverbose.txt](https://github.com/luisbocanegra/plasma-smart-video-wallpaper-reborn/files/15055637/testmediaplayeroutverbose.txt)
> 
> Interesting observation: pausing and unpausing works for the little chrome dongle clip, but not the other one.

Yeah, it seems it didn't like a couple of changes I made, reverted them and now those tests run fine for me.

> So, I think I solved the black screen issue (if not the "can't start after pausing" issue--want me to open that as a new one or just rename this?), 

Is this "can't start after pausing" present on the wallpaper itself? If so, please open a new issue.

> but I'll note again if things didn't work: my wallpaper files were on another drive. When I moved those over to my home partition instead, rebooting and just shutting down and starting normally seems to have things start up perfectly fine.

> Although, those other drives are mounted on startup too, so not sure why that would present an issue, but it's all I can really imagine is influencing it.

Strange, did you test rebooting multiple times to verify it was the only reason they didn't load?

**Comment by RainehDaze** [comment]
> Strange, did you test rebooting multiple times to verify it was the only reason they didn't load?

Yup, rebooted about half a dozen times now. No issues starting the initial video playback.

**Comment by RainehDaze** [comment]
> > Strange, did you test rebooting multiple times to verify it was the only reason they didn't load?
> > Yup, rebooted about half a dozen times now. No issues starting the initial video playback.
> 
> Thanks, I have a secondary drive with a ntfs partition that is also mounted on boot, tried loading a couple of videos from there and after rebooting two times in a row they loaded fine, will keep it that way to see if it happens at some point.

Might also be a drive speed issue? Not sure there--it _shouldn't_ be, the other drive was still an SSD, it shouldn't matter my boot drive is NVME.

**Comment by luisbocanegra** [comment]
Mine is HDD and boot one is NVME, maybe is some sort of bug with reading from other disks?

Or there is a problem with playback which could be instead caused by certain GPUs or combination of them as I use mostly Intel Graphics (Nvidia card disabled) and never had playback issues in my testing.

**Comment by RainehDaze** [comment]
Think it might be an X/Wayland session thing? Since running Wayland on Nvidia is still dicey if you don't like flicker.

**Comment by luisbocanegra** [comment]
> Think it might be an X/Wayland session thing? Since running Wayland on Nvidia is still dicey if you don't like flicker.

Maybe, I only tried wayland and ffmpeg backend and it worked. Yeah the flickers are the reason I still can't use it (or the lag when iGPU is the primary renderer)

**Comment by RainehDaze** [comment]
Yeah, I've been using the X Session until explicit sync is available, I'll keep an eye on stuff like that. Good few months for me to gather data on other random stuff, at least. :)
