### ISSUE TITLE
Videos Won't Unpause

### ISSUE THREAD

**Issue by RainehDaze** [luisbocanegra/plasma-smart-video-wallpaper-reborn#13]
If a pause condition is triggered (e.g. window is maximised on that screen), then when the condition is no longer true, the video in question doesn't resume playback. This includes setting the condition to 'never' afterwards and clicking apply--only restarting entirely or resetting the wallpaper to some other option then back to a smart video will cause it to play normally.

[sysinfo.txt](https://github.com/luisbocanegra/plasma-smart-video-wallpaper-reborn/files/15068603/sysinfo.txt)

As noted, have something of the same unpausing issue running the test scripts, don't know if the debug trace will contain anything about that:
[testout.txt](https://github.com/luisbocanegra/plasma-smart-video-wallpaper-reborn/files/15068606/testout.txt)

**Comment by luisbocanegra** [comment]
> If a pause condition is triggered (e.g. window is maximised on that screen), then when the condition is no longer true, the video in question doesn't resume playback. This includes setting the condition to 'never' afterwards and clicking apply--only restarting entirely or resetting the wallpaper to some other option then back to a smart video will cause it to play normally.

Does this happen every time? I am on wayland + Intel iGPU and pausing resuming works every time

> As noted, have something of the same unpausing issue running the test scripts, don't know if the debug trace will contain anything about that

If you use the updated test file does this still happen?

I suspect this could be a gpu related issue, also the focus from qt is now on ffmpeg, what happens if you use that instead? are there any crashes when running the wallpaper or the test file with ffmpeg backend?

**Comment by RainehDaze** [comment]
> Does this happen every time? I am on wayland + Intel iGPU and pausing resuming works every time

Yeah, every time. Nvidia and X, though, but I don't think it happened when I was using FFMPEG.

> If you use the updated test file does this still happen?

Yup, was using the new test file.

> I suspect this could be a gpu related issue, also the focus from qt is now on ffmpeg, what happens if you use that instead? are there any crashes when running the wallpaper or the test file with ffmpeg backend?

I'll give that a go--I swapped off it to try and fix the reboot black screens. Just delete the config file and it should go back to ffmpeg instead, right?

**Comment by luisbocanegra** [comment]
> I'll give that a go--I swapped off it to try and fix the reboot black screens. Just delete the config file and it should go back to ffmpeg instead, right?

Yes, after logging out it should be back to ffmpeg, you can confirm by echoing the environment variable to make sure it is no longer set

**Comment by RainehDaze** [comment]
Yup, looks like ffmpeg as a backend fixes that issue. Weirdly, it turns out the start of one of the test video clips wasn't playing using gstreamer, that was _very_ curious.

My recommendation for anyone running nvidia on X (and honestly, probably sensible in general, unless you can really help it): keep the files on the same drive, keep using ffmpeg.

**Comment by luisbocanegra** [comment]
Good, will add a note about these things to the readme. Thanks
