### ISSUE TITLE
support for gifs?

### ISSUE THREAD

**Issue by vk8a8** [luisbocanegra/plasma-smart-video-wallpaper-reborn#14]
will/can this hav e support for gifs? or isnot necessary?

**Comment by luisbocanegra** [comment]
Plasma already supports gifs as wallpapers with the default Image plugin. Is there any specific reason you would like to use this plugin to display gifs?

**Comment by vk8a8** [comment]
hi, for feature to pause whilst not looking at it. thinking it could put slight strain on my system.

**Comment by luisbocanegra** [comment]
Thanks, I can look into adding the pause wallpaper feature to my other [Wallpaper Effects](https://github.com/luisbocanegra/plasma-wallpaper-effects) widget. If it's not possible I may consider adding support for gifs to this widget in the future.

**Comment by vk8a8** [comment]
will be looking foreward. my gratitude

**Comment by vk8a8** [comment]
i found that this feature was already build in. silly me!

**Comment by luisbocanegra** [comment]
Nice! [Looking at the code](https://invent.kde.org/plasma/plasma-workspace/-/blob/master/wallpapers/image/imagepackage/contents/ui/mediacomponent/AnimatedImageComponent.qml?ref_type=heads) I see they pause for maximized windows on the screen the wallpaper is in.
