### ISSUE TITLE
Per-Video Settings

### ISSUE THREAD

**Issue by RomanKode** [luisbocanegra/plasma-smart-video-wallpaper-reborn#15]
I have an idea for the video list, it would be good if the videos that I add have some basic settings, in this case, loop/repeat and a loop count, there are videos that are short and when using multiple videos they do not last long, it would be great to add loop counts before switching, another way could be to set a total run time, like run each video for 2 minutes(can be adjusted) before switching then using a crossfade(would like to see this regardless of this feature) effect to smooth the transition between current and next video, another option would be to make a randomizer, it should take the list order, randomize then play it at the randomized order.

**Comment by luisbocanegra** [comment]
Those are some good suggestions, will try to implement them in upcoming versions

**Comment by luisbocanegra** [comment]
Started working on the crossfade feature, still somewhat buggy but looks really nice.

https://github.com/luisbocanegra/plasma-smart-video-wallpaper-reborn/assets/15076387/97b4b6ec-b7e7-4201-9d93-365e4d8145db

**Comment by luisbocanegra** [comment]
Hi I split this issue into separate ones so they're easier to find/track
