### ISSUE TITLE
GPU usage 2-3x more than playing back videos directly

### ISSUE THREAD

**Issue by TheOverpassArsonist** [luisbocanegra/plasma-smart-video-wallpaper-reborn#18]
On an nvidia 3080 with the latest packages from the arch repos and two 1080p displays I'm getting 2-3x higher GPU usage playing videos as my desktop than I am if I play the videos in full screen in a seperate player like Haruna. 

With no active videos playing and my cursor still I rest at ~0% GPU usage. (which makes sense as literally nothing is actually happening on screen)
With [this](https://www.videezy.com/backgrounds/54455-lively-party-like-dimensional-loop-hole) video playing in full screen in Haruna using the nvdec hardware decoder I rest at about 10%
With that video playing as my desktop background I rest at about 30%.
With that video playing as _both_ of my desktop backgrounds it fluctuates a lot more, but tends to sit around 45-50%
(with it playing on both monitors fullscreen in Haruna it's around 20%)

I've tested with several videos and it is consistently around 2-3x more resource intensive to run them as my background than play them directly, and I'm not sure why that is. I'd wager that the reason that two videos isn't quite 2x as intensive is that my monitors don't refresh at the same rate. My left monitor is 120hz and my right monitor is 75hz. Notably though, those differing refresh rates don't effect Haruna which does simply double to 20% usage, so I'm guessing part of the resource loss has something to do with the monitor refresh rate, with higher refresh rates requiring more resources to play the same video.

On the matter of performance there are two additional notes that I wanted to add but felt way too minor to be their own things, 1st : would it be possible to 'share' resources between monitors? Maybe I'm wrong (I have very little reference here) but if you're playing the same video on both desktops, it seems like you could just mirror the content for near-free since you only need to decode it once. 2nd : would it be possible to generate basically an LOD version of the video? In other words instead of outright pausing the video instead start playing a lower-resolution version of the video, with the reduced resolution being made up for by the blur-effect. Not sure if that's even a little bit possible to do, but it'd allow the video to play non-stop while using a fraction of the resources. This would keep multi-monitor setups more cleanly in sync. Amazingly the pausing/resuming is basically seamless, but if one display has a fullscreen application which makes the video pause and the other doesn't then they will desync which can be quite noticable depending on the video you use. Additionally an LOD system would probably make translucent windows look nicer, but I don't use any translucent window rules myself so I can't speak for that

**Comment by luisbocanegra** [comment]
I have seen the increased GPU usage too in  both Intel integrated graphics and Nvidia. Not sure if it's just how it is or some configuration can improve this, that needs to be investigated.

> On the matter of performance there are two additional notes that I wanted to add but felt way too minor to be their own things, 1st : would it be possible to 'share' resources between monitors? Maybe I'm wrong (I have very little reference here) but if you're playing the same video on both desktops, it seems like you could just mirror the content for near-free since you only need to decode it once. 2nd : would it be possible to generate basically an LOD version of the video? In other words instead of outright pausing the video instead start playing a lower-resolution version of the video, with the reduced resolution being made up for by the blur-effect. Not sure if that's even a little bit possible to do, but it'd allow the video to play non-stop while using a fraction of the resources. This would keep multi-monitor setups more cleanly in sync.

> Amazingly the pausing/resuming is basically seamless, but if one display has a fullscreen application which makes the video pause and the other doesn't then they will desync which can be quite noticable depending on the video you use. Additionally an LOD system would probably make translucent windows look nicer, but I don't use any translucent window rules myself so I can't speak for that

Maybe, but that will require adding C++ and knowing about video/graphics and I don't have either. Not sure if the effort would be worth the benefit. [wallpaper-engine-kde-plugin](https://github.com/catsout/wallpaper-engine-kde-plugin) supports mpv maybe you could try that to see how it performs

**Comment by luisbocanegra** [comment]
Hi. Please download the file below and run `kpackagetool6 -t Plasma/Wallpaper -u plasma-smart-video-wallpaper-reborn-v0.2.1.zip`, reboot/re-login and try with a single video first then multiple while `journalctl -f > journal.txt` is running.

Let me know if there is any improvement on both 3D and video decoding usage

[plasma-smart-video-wallpaper-reborn-v0.2.1.zip](https://github.com/luisbocanegra/plasma-smart-video-wallpaper-reborn/files/15477359/plasma-smart-video-wallpaper-reborn-v0.2.1.zip)

**Comment by luisbocanegra** [comment]
Moving shared resources topic to https://github.com/luisbocanegra/plasma-smart-video-wallpaper-reborn/issues/23

**Comment by luisbocanegra** [comment]
The GPU usage should be fixed in the latest release https://github.com/luisbocanegra/plasma-smart-video-wallpaper-reborn/releases/tag/v0.4.0

When blur is not showing, the usage should now be more or less the same as `mpv --profile=fast video.mp4`

**Comment by TheOverpassArsonist** [comment]
Sorry for the delay, life got really complicated for a bit and I ended up forgetting about this entirely. I can confirm however that with the most recent version the GPU load appears to be minimal. (it even appears to not use anymore more resources if played on two monitors at once? When testing this it wasn't quite consistent but it seems to be the case) 

There is still the issue of keeping them in sync if one gets paused, but now that the performance problems have been mitigated that's more of a quality of life issue than a performance issue since it playing in the background unnecessarily is no longer as draining on system resources.

**Comment by luisbocanegra** [comment]
Thanks a lot for the confirmation.

> (it even appears to not use anymore more resources if played on two monitors at once? When testing this it wasn't quite consistent but it seems to be the case)

In my case still uses around 5% more gpu instead of doubling, the decoding still increases around 2x but I think that's acceptable while still using only QML

> There is still the issue of keeping them in sync if one gets paused, but now that the performance problems have been mitigated that's more of a quality of life issue than a performance issue since it playing in the background unnecessarily is no longer as draining on system resources.

Tracking that one here https://github.com/luisbocanegra/plasma-smart-video-wallpaper-reborn/issues/36

**Comment by OneNot** [comment]
I seem to be having this same issue...
I'm not going to reopen this as of yet, but maybe you @luisbocanegra might have an idea if I'm doing something wrong and what to do? Or has the issue really resurfaced?

Here are some notes I took during some basic testing:

## Video wallpaper HW decoding tests
- CachyOS (Arch), KDE Plasma (Wayland)
- CPU: 13900K
- GPU: RTX4090
- Monitors: 2x 3440 x 1440
- Test video used: 30s long, h264, 1920x1080, 60 fps
### Haruna video playback at fullscreen (single screen)
- nvdec: gpu ~20%, cpu 0.8-1.5%
	- nvtop Shows GPU as decoding
- vaapi: gpu ~15-17%, cpu 0.8-1.5%
	- nvtop Shows GPU as decoding... Why/How? Isn't VAAPI Intel and AMD only?
		- Using iGPU? Though I think I have it disabled in the BIOS? `inxi -G` only shows my 4090.
- disabled: gpu ~8%, cpu ~1-2%
	- Others below are just falling back to software decoding (not showing decoding in nvtop)
		- cuda: gpu ~10%, cpu ~1-2%
		- videotoolbox ~10%, cpu ~1-2%
		- d3d11va: gpu ~10%, cpu ~1-2%
### Same video in Smart Video Wallpaper Reborn
- GPU mostly **~50-60%** (single screen)
	- If on both monitors, GPU mostly **~60-70%**
	- Occasional dips to ~20-30%
- CPU 1-2%

**Comment by luisbocanegra** [comment]
Yeah... this is still a thing it seems.

Testing with https://github.com/luisbocanegra/plasma-smart-video-wallpaper-reborn/tree/mpvqt-plugin branch the gpu usage halves so there is definitely an overhead of using Qt Multimedia

**Comment by OneNot** [comment]
Are you reopening this issue then?
I'd like to track this so I get a notification if you figure it out at some point...

60-70% GPU usage on "idle" is simply too much for my taste, so I won't be using this right now. Honestly I'm of two minds whether to use video wallpapers at all, but if this issue did get solved and I could get them with much lower GPU usage, I would reconsider...

Either way, no pressure. I wish you luck.

**Comment by luisbocanegra** [comment]
Reopened, aside from developing and testing I don't use this plugin myself anymore, so it may take a while for me to come back to this
