### ISSUE TITLE
Video Stops After Half Second In Lockscreen

### ISSUE THREAD

**Issue by leuchtrakete666** [luisbocanegra/plasma-smart-video-wallpaper-reborn#20]
I have installed the plugin with AUR. The desktop wallpaper works. But I don't need this. I want to have the lockscreen video.

But this stops after half second. Nothing crashes, no freeze, just the video stops.

The test.qml runs fine.

[dmesg.txt](https://github.com/user-attachments/files/15823432/dmesg.txt)
[journal.txt](https://github.com/user-attachments/files/15823433/journal.txt)
[lspci.txt](https://github.com/user-attachments/files/15823434/lspci.txt)
[qml_video_test_log.txt](https://github.com/user-attachments/files/15823435/qml_video_test_log.txt)
[sysinfo.txt](https://github.com/user-attachments/files/15823440/sysinfo.txt)

**Comment by luisbocanegra** [comment]
Hi, please check that **Lock screen mode** is enabled the wallpaper settings. I can reproduce the exact behavior after disabling it

**Comment by leuchtrakete666** [comment]
Only yesterday, I set up the system fresh, after the Plasma 6 upgrade made some problems. One of the problems was your plugin. But unfortunetly, all the effort was invane. The plugin still don't work and all the other small issues, that f*** my workflow are still present. A really bugy release. I really like Arch and Manjaro, but in this case, they should have waited at least 3-4 month longer until they let the upgrade out in the wild.

**Comment by luisbocanegra** [comment]
Sorry I overlooked something in your log (translated) it seems to be something wrong in your system:

```
Jun 13 17:21:54 ZEUS ksmserver[4576]: Failed to open VDPAU backend libvdpau_va_gl.so: Cannot open the shared object file: File or directory not found
Jun 13 17:21:54 ZEUS ksmserver[4576]: [h264_cuvid @ 0x59075b7c0900] Invalid pkt_timebase, passing timestamps as-is.
```

**Comment by leuchtrakete666** [comment]
I resolved the VDPAU error by installing libvdpau_va_gl driver package and setting env `VDPAU_DRIVER=va_gl`. Unfortunetly this did not resolve the problem.

I have a hybrid intel/nvidia laptop. maybe this is the problem.

I just looked in the journal when using a video background for the desktop. The same h264_cuvid error show there also. But on the desktop the video is working.

With the Plasma5 version of the plugin, everything worked.

I have no idea.

**Comment by luisbocanegra** [comment]
> I have a hybrid intel/nvidia laptop. maybe this is the problem.

It could be, forcing the intel to do the decoding https://wiki.archlinux.org/title/Hardware_video_acceleration#Configuring_VA-API may work, you could also try switching to gstreamer backend as per the readme

**Comment by leuchtrakete666** [comment]
Nope, also don't work. As it worked in Plasma 5, i think KDE changed something in the way the screenlock is handled.

**Comment by luisbocanegra** [comment]
Okay here are some things you can try to verify if this is a problem with your install or naybe nvidia related:

- Try another distribution (maybe a live USB with one that ships KDE, nvidia proprietary driver and codecs will be enough to test)
- Disable either of the GPUs in some way (bios, blacklisting from boot loader, or simply setting the [KWin DRM environment variable](https://www.reddit.com/r/kde/comments/1ainwf5/how_i_worked_around_poor_performance_with/))

**Comment by leuchtrakete666** [comment]
Thanks for the tips, this would have been also my next steps. This Reddit post I also found whilst my research and found it very interesting. The X-Server is running on my Nvidia and all the rest is on Intel.

I will do some testing over the weekend.

**Comment by NietVic** [comment]
Hi I was had the same issue you should make sure that the setting screen lock pauses video is disabled before entering lock screen mode.
![Screenshot_20240618_141248](https://github.com/luisbocanegra/plasma-smart-video-wallpaper-reborn/assets/96957521/37d9cc01-3c2e-48e0-bc10-ff8d3f651105)

**Comment by leuchtrakete666** [comment]
@NietVic 
Hey, thats cool! Great it works now. Thanks for this easy solution. 

@luisbocanegra 
Would be good if `Lock screen mode` is selected, `Screen lock pauses video` will be automatically deactivated.

**Comment by luisbocanegra** [comment]
> Would be good if Lock screen mode is selected, Screen lock pauses video will be automatically deactivated.

Done in commit https://github.com/luisbocanegra/plasma-smart-video-wallpaper-reborn/commit/c488173035e138f87fec60a354e2e4a171bb6449

@NietVic thank you.
