### ISSUE TITLE
Panel Question

### ISSUE THREAD

**Issue by proatgram** [luisbocanegra/plasma-smart-video-wallpaper-reborn#22]
Just a general question, in the demo video I am curious as to what you used to make the panel like that? I used to use Latte Dock to perform something similar but Latte Dock no longer works in Plasma 6.

**Comment by luisbocanegra** [comment]
Hi, it's https://github.com/luisbocanegra/plasma-panel-colorizer

**Comment by proatgram** [comment]
Thanks for the quick reply! I'll check it out!
