### ISSUE TITLE
Video is stuck on lock screen but works as desktop wallpaper

### ISSUE THREAD

**Issue by archisman-panigrahi** [luisbocanegra/plasma-smart-video-wallpaper-reborn#27]
I am using Arch Linux with Plasma 6.1

The plugin works perfectly as a desktop wallpaper, but when I apply it in the lock screen, the video plays for a fraction of a second, and then pauses.

How to debug?

I checked with nvtop that the Intel GPU is detected
```
 Device 0 [CoffeeLake-S GT2 (UHD Graphics 630)] Integrated GPU RX: N/A TX: N/A
```

I did not face any black screen error.

**Comment by archisman-panigrahi** [comment]
Sorry, did not see the "Lock Screen Mode" button. Thanks for making this awesome plugin.

**Comment by luisbocanegra** [comment]
You're welcome. I will add a note about that to the readme. Later I could try to find a way to detect from within the wallpaper if it's being used in the lock screen and enable that automatically.
