### ISSUE TITLE
mp4 files aren't runing correctly, gifs are

### ISSUE THREAD

**Issue by GNJAL** [luisbocanegra/plasma-smart-video-wallpaper-reborn#42]
I have noticed that mp4 files in particular tend to stutter after trying to loop the file. It has never smoothly looped the video and often causes the wallpaper to freeze. When it starts moving again it doesn't start from the beginning of the file, which indicates that it's still running even though the wallpaper just freezes. Any fixes?

When I tried out a gif file it just worked. Everything!

I'm using Fedora 40 KDE Plasma. I don't think I have hardware acceleration on either.

**Comment by luisbocanegra** [comment]
Please [verify and enable hardware acceleration if it's not enabled](https://fedoraproject.org/wiki/Firefox_Hardware_acceleration#Video_decoding) first, and test with a small file like [this one](https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4) it should play just fine.

If hardware acceleration is enabled and still stutters please do the following:

Try with smaller files preferably something that matches your monitor resolution and you know your hardware can handle. If everything lags follow the steps below.

1. Run `journalctl -f > journal.txt` and `sudo dmesg -wHT > dmesg.txt` in separate terminals
2. While both commands are running switch from the Image wallpaper plugin to video wallpaper and reproduce the issue
3. Then stop both commands
4. Get your system information from `kinfo`
5. Run `lspci -k | grep -EA3 'VGA|3D|Display' > lspci.txt`
6. Screenshot of the wallpaper plugin configuration

Attach the outputs and files here

**Comment by GNJAL** [comment]
It works now.
I got hardware acceleration to work, and yes it honestly did take me a week. I was originally using it with an even smaller file and it was stuttering. It does seem that disabled hardware acceleration was the problem.
