### ISSUE TITLE
[Question] Use intergrate GPU explicitly

### ISSUE THREAD

**Issue by TTsdzb** [luisbocanegra/plasma-smart-video-wallpaper-reborn#44]
I'm using a gaming laptop with two GPUs, an AMD intergrated one and a NVIDIA discrete one. As `nvtop` shows, the wallpaper is decoded on the discrete one, but I would like to use the intergrated one to save some power.

![image](https://github.com/user-attachments/assets/5b37123a-cc4e-4fa2-859b-227f404dc437)

I've tried setting `LIBVA_DRIVER_NAME=radeonsi` in `~/.config/plasma-workspace/env/libva-driver-name.sh`, but it seems not working.

I tried mpv and it uses intergrated GPU without any environment variables:

```
$ mpv --hwdec=auto Wind_blow\ 1080P.mp4
● Video  --vid=1  (h264 1920x1080 30 fps) [default]
● Audio  --aid=1  (aac 2ch 44100 Hz 129 kbps) [default]
Using hardware decoding (vaapi).
AO: [pipewire] 44100Hz stereo 2ch floatp
VO: [gpu] 1920x1080 vaapi[nv12]
AV: 00:00:21 / 00:01:40 (21%) A-V:  0.000
Exiting... (Quit)
```

![image](https://github.com/user-attachments/assets/6efe228e-bcfd-4b89-bc45-97a151c0d567)

**Comment by TTsdzb** [comment]
`VDPAU_DRIVER=radeonsi` does not do the work, either

**Comment by luisbocanegra** [comment]
It seems somewhere in qt is not checking the environment variable and it uses the main gpu instead? (just a guess)

What happens if you try setting KWIN_DRM_DEVICES as explained here https://www.reddit.com/r/kde/comments/1ainwf5/how_i_worked_around_poor_performance_with/ does the gpu used for video decoding change?

**Comment by TTsdzb** [comment]
Well it still not working...

Here's my `/etc/udev/rules.d/legion-r7000p-drm-devices.rules`:

```
# Specifically for Lenovo Legion R7000P 2021H laptop. Other models are not guranteed to work!
KERNEL=="card*", DRIVERS=="amdgpu", SYMLINK+="dri/by-type/integrated"
KERNEL=="card*", DRIVERS=="nvidia", SYMLINK+="dri/by-type/discrete"
```

```
$ l /dev/dri/by-type  
lrwxrwxrwx root root 8 B Mon Sep 30 15:53:09 2024  discrete ⇒ ../card0
lrwxrwxrwx root root 8 B Mon Sep 30 15:53:09 2024  integrated ⇒ ../card1
```

`/etc/environment`:

```
# We prefer to use integrated GPU instead of discrete one
# Must be used with specific udev rules
# https://www.reddit.com/r/kde/comments/1ainwf5/how_i_worked_around_poor_performance_with/
KWIN_DRM_DEVICES=/dev/dri/by-type/integrated:/dev/dri/by-type/discrete
```

**Comment by TTsdzb** [comment]
Should I set this env in `~/.config/plasma-workspace/env/`?

**Comment by TTsdzb** [comment]
Should plasmashell run on all GPUs of a computer? I wonder if it's caused by my plasmashell running on the discrete one.

```
$ nvidia-smi
Mon Sep 30 16:19:03 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 560.35.03              Driver Version: 560.35.03      CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3060 ...    Off |   00000000:01:00.0 Off |                  N/A |
| N/A   43C    P8             11W /   80W |     191MiB /   6144MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A       867      G   /usr/lib/Xorg                                   4MiB |
|    0   N/A  N/A      1526      C   /usr/bin/plasmashell                          172MiB |
+-----------------------------------------------------------------------------------------+
```

**Comment by luisbocanegra** [comment]
> Should plasmashell run on all GPUs of a computer?

AFAIK that depends on whatever the system picks up as the default GPU

> Should I set this env in ~/.config/plasma-workspace/env/?

which you should be able to override with KWIN_DRM_DEVICES in /etc/environment, I use it sometimes when I need to use the dedicated gpu to make it the primary and avoid the issues mentioned in the reddit post.

To check if that environment variable is working run `glxinfo | grep -E "OpenGL vendor|OpenGL renderer"` and you should get the gpu name there

But even with that, at least for me with the intel gpu set as primary, qt-multimedia (what the wallpaper uses) still uses the nvidia card to do the decoding, so this seems to be missing / broken from Qt itself or somewhere else.

Found this issue that seems related https://bugreports.qt.io/browse/QTBUG-122757?jql=text%20~%20%22LIBVA_DRIVER_NAME%22 can you try the environment variables listed there?

**Comment by TTsdzb** [comment]
> Found this issue that seems related https://bugreports.qt.io/browse/QTBUG-122757?jql=text%20~%20%22LIBVA_DRIVER_NAME%22 can you try the environment variables listed there?

This ends the match. A simple `QT_FFMPEG_DECODING_HW_DEVICE_TYPES="vaapi"` will do the work, even without `LIBVA_DRIVER_NAME`. Obviously it uses something else by default (and may not be VDPAU, since its envs are not working, either).

I wonder if this helps on #10.

**Comment by mcfd** [comment]
> > Found this issue that seems related https://bugreports.qt.io/browse/QTBUG-122757?jql=text%20~%20%22LIBVA_DRIVER_NAME%22 can you try the environment variables listed there?
> 
> This ends the match. A simple `QT_FFMPEG_DECODING_HW_DEVICE_TYPES="vaapi"` will do the work, even without `LIBVA_DRIVER_NAME`. Obviously it uses something else by default (and may not be VDPAU, since its envs are not working, either).
> 
> I wonder if this helps on [#10](https://github.com/luisbocanegra/plasma-smart-video-wallpaper-reborn/issues/10).
> 
> Anyway, thanks for your help.

useful for nvidia RTD3
