### ISSUE TITLE
[Request] Let users choose iGPU or dGPU to render the video

### ISSUE THREAD

**Issue by riarumoda** [luisbocanegra/plasma-smart-video-wallpaper-reborn#45]
I requested this since i got a similar problems with #44 but the difference is i got a full AMD laptop, which is the usual AMD iGPU and a RX 7600S as dGPU, and both loads the same amdgpu driver, which killing the KWIN_DRM_DEVICES trick. (Might need to dig more on this one), i also tried QT_FFMPEG_DECODING_HW_DEVICE_TYPES which is also didn't work. another reason is because the dGPU consumes 15w to just render the video itself, which is already a lot considering the iGPU already eat 25w for the whole desktop.

and i dont think this one is related to #10 since i can load 4K videos without issues.

**Comment by luisbocanegra** [comment]
Unfortunately there doesn't seem to be a way to do that when both cards use the same driver

https://doc.qt.io/qt-6/advanced-ffmpeg-configuration.html
> The FFmpeg plugin chooses the hardware acceleration backend for decoding and encoding based on availability, stability, efficiency, and implementation details. If the selected hardware backend doesn't work as expected, you can try setting a custom priority list or disable all the hardware backends via the environment variables

> Examples:
> ```
> # Set vdpau or cuda encoding hardware backends
> export QT_FFMPEG_ENCODING_HW_DEVICE_TYPES=vdpau,cuda
> 
> # Set only d3d12va decoding hardware backend
> export QT_FFMPEG_DECODING_HW_DEVICE_TYPES=d3d12va
> 
> # Disable decoding hw backends (set an empty list)
> export QT_FFMPEG_DECODING_HW_DEVICE_TYPES=,
> ```

Unless there is an undocumented environment variable to do this I don't think is possible to specify a card when both use the same driver

> usual AMD iGPU and a RX 7600S as dGPU, and both loads the same amdgpu driver, which killing the KWIN_DRM_DEVICES trick. (Might need to dig more on this one)

You can just try swapping them around e.g `export KWIN_DRM_DEVICES=card0:card1` or `export KWIN_DRM_DEVICES=card1:card0` but as found in #44 this will most likely do nothing

**Comment by riarumoda** [comment]
Solved! my paramenter on `/etc/environment` is this to force the video to render on iGPU instead:
```
QT_FFMPEG_DECODING_HW_DEVICE_TYPES=vulkan,vdpau
KWIN_DRM_DEVICES=/dev/dri/card2:/dev/dri/card1
```

it's probably the QT_FFMPEG_DECODING_HW_DEVICE_TYPES doing the work, but still it's better to point out which GPU is the iGPU and dGPU.

**Comment by luisbocanegra** [comment]
Interesting, would be nice if you could confirm if changing `KWIN_DRM_DEVICES` is needed in this case so I can add it to the readme, could be useful not only to save resources but also for those with crashes black screen like https://github.com/luisbocanegra/plasma-smart-video-wallpaper-reborn/issues/8

**Comment by luisbocanegra** [comment]
Also since everything will be running on the iGPU now it will affect which GPU is used for games so you might need to change that back to the dGPU in steam and the like

**Comment by riarumoda** [comment]
> Interesting, would be nice if you could confirm if changing `KWIN_DRM_DEVICES` is needed in this case so I can add it to the readme, could be useful not only to save resources but also for those with crashes black screen like #8

I just checked it and nothing happens, still rendering on the igpu.
