### ISSUE TITLE
Cannot use on NixOS Plasma 6

### ISSUE THREAD

**Issue by MinallW** [luisbocanegra/plasma-smart-video-wallpaper-reborn#46]
On a new installation of NixOS Plasma6, I can install the plugin via the settings, but there's no buttons to interact with it like they are in demonstration videos.

![image](https://github.com/user-attachments/assets/aa802910-cba8-4671-b950-7a079a337266)

So, I cannot use this plugin, perhaps I need to install something? (My desktop is black btw)

Thanks!

**Comment by luisbocanegra** [comment]
Could be a missing qml plugin, can you run `journalctl -f`, launch the wallpaper settings, switch to video wallpaper as shown in your screenshot then paste the output here?

**Comment by MinallW** [comment]
oct 21 01:02:43 nixos plasmashell[1374]: kf.coreaddons: "Could not find plugin luisbocanegra.smart.video.wallpaper.reborn"
oct 21 01:02:43 nixos plasmashell[1374]: QQmlComponent: Component is not ready
oct 21 01:02:43 nixos plasmashell[1374]: file:///nix/store/fsk88iimagskplidppw5mgd00p5hr968-plasma-desktop-6.0.5/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml:130:9: QML StackView: replace: file:///home/minall/.local/share/plasma/wallpapers/luisbocanegra.smart.video.wallpaper.reborn/contents/ui/config.qml:26 module "QtMultimedia" is not installed
