### ISSUE TITLE
Enable Hardware Acceleration.

### ISSUE THREAD

**Issue by LiveWallpaperReborn** [luisbocanegra/plasma-smart-video-wallpaper-reborn#9]
The instructions for enabling hardware acceleration are unclear/insufficient. I've gone through the linked Arch Wiki, and I believe I have everything installed. Nvidia 2070 Super. (Also Fuck Nvidia) From my research enabling hardware acceleration isn't just something you do on an OS level like your instructions make it out to be (but i'm also retarded though, so maybe it is). The following instructions to enable hardware acceleration in FFMPEG and Gstreamer seemed to make sense at first, but after digging on how to do that, it appears that you don't just enable hardware acceleration in FFMPEG, but instead specify for the program to use it when you're encoding a video, for example. Honestly i'm not very familiar with FFMPEG and always use a gui wrapper. I was hoping you could make it more clear what specific underlying program is running the video, and what specific changes your end users would need to make to enable it to run on the GPU. 

For me specifically i'm running Nvidia proprietary drivers on the latest Endeavour OS. (That's basically Arch, btw)

As it stands my CPU runs around 20% from KDE when video wallpaper is on.

Ps. This reimplimentation of smart video wallpaper is fucking phenomenal. the video start stop on window maximize is instant! infinitely smoother than the original that would sometimes take up to 5 seconds to restart the video. You must have done some serious code optimization. This plugin is better than the original, and smartER video wallpaper. I was very upset when I saw it wasn't ported to plasma 6 when Endeavour updated. So, seriously man... thank you. I like the interface a lot more too, and it seems  simpler to use as a whole and more powerful, as well. multi video support is badass!

So again, Thanks. Seriously.

**Comment by luisbocanegra** [comment]
> The instructions for enabling hardware acceleration are unclear/insufficient. I've gone through the linked Arch Wiki, and I believe I have everything installed. Nvidia 2070 Super. (Also Fuck Nvidia) From my research enabling hardware acceleration isn't just something you do on an OS level like your instructions make it out to be (but i'm also retarded though, so maybe it is). The following instructions to enable hardware acceleration in FFMPEG and Gstreamer seemed to make sense at first, but after digging on how to do that, it appears that you don't just enable hardware acceleration in FFMPEG, but instead specify for the program to use it when you're encoding a video, for example.

The commandline stuff can be ignored. If there are additional dependencies that are not listed in the main [Hardware video acceleration](https://wiki.archlinux.org/title/Hardware_video_acceleration) page they should be installed. But for Nvidia proprietary driver + ffmpeg backend (which is the default) only `nvidia-utils` additional package should be needed.

> Honestly i'm not very familiar with FFMPEG and always use a gui wrapper. I was hoping you could make it more clear what specific underlying program is running the video, and what specific changes your end users would need to make to enable it to run on the GPU.

The video is played by [Qt Multimedia](https://doc.qt.io/qt-6/qtmultimedia-index.html), which has a qml plugin that internally uses ffmpeg (or gstreamer if forced with the environment variable). The specific code that plays the video is located in [main.qml](https://github.com/luisbocanegra/plasma-smart-video-wallpaper-reborn/blob/75d39ad8b1ed859c39125cee86110cbbc27eeb35/package/contents/ui/main.qml#L95) so as you can see it is not running ffmpeg or gstreamer commands directly.

> For me specifically i'm running Nvidia proprietary drivers on the latest Endeavour OS. (That's basically Arch, btw)
> 
> As it stands my CPU runs around 20% from KDE when video wallpaper is on. 

I just tried booting with only the nvidia card enabled and it works with hw acceleration. All I did was install the proprietary driver + `nvidia-utils` and set `LIBVA_DRIVER_NAME=nvidia` environment variable. I'm using the default ffmpeg backend.

| Nvidia | Intel |
| --- | --- |
| ![Screenshot_20240404_064105](https://github.com/luisbocanegra/plasma-smart-video-wallpaper-reborn/assets/15076387/750ce39c-0cbd-41b2-9cc2-6a09f21ad3c2) This is on a laptop with two monitors + GTX 1650 (weak) + intel gpu, the iGPU is only used to display output from the main renderer (which is the Nvidia card) to the laptop's screen | ![Screenshot_20240404_075849](https://github.com/luisbocanegra/plasma-smart-video-wallpaper-reborn/assets/15076387/e5855ce5-06af-404c-95e6-a01f10c3cce7) For reference, same two displays, Intel gpu only with hw acceleration as you can see in `intel_gpu_top`|

The video playing is in 4K and cpu/gpu load is still somewhat high but as you can see in nvtop `DEC: 26%` it is using the gpu for video decoding, same for the Intel gpu on the right.

Can you please install and run nvtop and show the output you get?

> Ps. This reimplimentation of smart video wallpaper is fucking phenomenal. the video start stop on window maximize is instant! infinitely smoother than the original that would sometimes take up to 5 seconds to restart the video. You must have done some serious code optimization. This plugin is better than the original, and smartER video wallpaper. I was very upset when I saw it wasn't ported to plasma 6 when Endeavour updated. So, seriously man... thank you. I like the interface a lot more too, and it seems simpler to use as a whole and more powerful, as well. multi video support is badass!
> 
> So again, Thanks. Seriously.

You're welcome! At first just wanted to make it work and send the patches to the old project, but seeing it wasn't really being maintained I decided to continue my own and just kept improving it.

**Comment by LiveWallpaperReborn** [comment]
thank you so much for your well thought out and complete reply! So, remember when I said I was retarded? Turns out I was hardware accelerating the whole time and found out with nvtop (thanks for that, btw. nvtop is awesome! Always bugged me htop never showed GPU usage. nvtop just got added to my list of programs in my post-install script) the cpu utilization is only 20% on one core, anyways, gpu is at like 20% while accelerating, and it all dies when i pull up a fullscreen app because unlike the original Smart Video Wallpaper your pause resume on maximized windows works flawlessly and instantly. that's easy to live with especially with the epic eye candy. I can't go back to jpeg's as wallpaper, man. :D

You may want to add a bit to the hardware encoding part of your readme for people like me something like (on most distro's its likely hardware acceleration is enabled out of the box. check nvtop for GPU utilization) . Always good to idiot proof something. :D

Ps. I thought i'd seen your name before and just noticed... 
![Panel Colorizer](https://github.com/luisbocanegra/plasma-smart-video-wallpaper-reborn/assets/165982553/9242d75f-81b0-47cf-beb3-00dd7bcd064a)
You make panel colorizer too?! how awesome can you be! you've basically made my whole desktop, man. I found colorizer on a forum post looking for a latte dock replacement. Pic attached of my desktop. It's literally all you, and colors by catpuccin. The KDE team should really just hire you on and integrate your plasma addons into mainline.

**Comment by luisbocanegra** [comment]
> thank you so much for your well thought out and complete reply! So, remember when I said I was retarded? Turns out I was hardware accelerating the whole time and found out with nvtop (thanks for that, btw. nvtop is awesome! Always bugged me htop never showed GPU usage. nvtop just got added to my list of programs in my post-install script) the cpu utilization is only 20% on one core, anyways, gpu is at like 20% while accelerating

Yeah I also noticed that, it seems video decoding on Nvidia may need some improvements. But knowing how things go with Nvidia+Linux I am thankful it works at least. Also surprises me AMD is the one [having](https://github.com/luisbocanegra/plasma-smart-video-wallpaper-reborn/issues/7) [problems](https://github.com/luisbocanegra/plasma-smart-video-wallpaper-reborn/issues?q=is%3Aissue+sort%3Aupdated-desc+amd+is%3Aopen) with this plugin.

> and it all dies when i pull up a fullscreen app because unlike the original Smart Video Wallpaper your pause resume on maximized windows works flawlessly and instantly. that's easy to live with especially with the epic eye candy. I can't go back to jpeg's as wallpaper, man. :D
> 
> You may want to add a bit to the hardware encoding part of your readme for people like me something like (on most distro's its likely hardware acceleration is enabled out of the box. check nvtop for GPU utilization) . Always good to idiot proof something. :D

Thanks for the suggestion, I'll add it to the readme.

> Ps. I thought i'd seen your name before and just noticed... ![Panel Colorizer](https://private-user-images.githubusercontent.com/165982553/319927577-9242d75f-81b0-47cf-beb3-00dd7bcd064a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzMTUwMzcsIm5iZiI6MTcxMjMxNDczNywicGF0aCI6Ii8xNjU5ODI1NTMvMzE5OTI3NTc3LTkyNDJkNzVmLTgxYjAtNDdjZi1iZWIzLTAwZGQ3YmNkMDY0YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNVQxMDU4NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMDFmOGEzMzY5NmU1Mzk0OTNmNzM5ZTlhNjNiZmRjY2I2NzEzM2ZmYjkyMmRjNTg2OWUwZjBhOTRiZjZlZGFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LrB5QUOKZD1Az0TeZ8IobrHzU1qZE4Sl0EyDQlqzpTc) You make panel colorizer too?! how awesome can you be! you've basically made my whole desktop, man. I found colorizer on a forum post looking for a latte dock replacement. Pic attached of my desktop. It's literally all you, and colors by catpuccin. The KDE team should really just hire you on and integrate your plasma addons into mainline.

Thanks for the kind words ❤️.  Unfortunately most of the plugins I make are experimental/overkill and susceptible to decreased accessibility/performance. Not to mention the ab(use) of qml, some of these things should be done in C++ which I know nothing of 🙃.
